name: checkout

version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 5.1.0
  sentry_flutter: 7.7.0
  translations_cleaner: 0.0.5
  device_preview: ^1.1.0

dev_dependencies:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: 1.0.3
  very_good_analysis: 5.0.0+1
  daunused: 1.3.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true

