name: checkout

version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  credit_card_validator: 2.1.0
  date_format: 2.0.7
  device_preview: 1.1.0
  eva_icons_flutter: 3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 8.0.1
  google_fonts: 5.1.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  lottie: 2.4.0
  path_provider: ^2.0.15
  provider: 6.0.5
  sentry_flutter: 7.7.0
  translations_cleaner: 0.0.5
  flutter_credit_card: 3.0.7

dev_dependencies:
  build_runner: 2.4.6
  daunused: 1.3.0
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0+1
  pubspec_dependency_sorter: 1.0.3
  very_good_analysis: 5.0.0+1

flutter:
  assets:
    - assets/images/
    - assets/images/provider_logos/
    - assets/lottis/

  uses-material-design: true
  generate: true
