name: 'Analyze App'
description: 'Formats and cleans project and then runs static analysis'
author: 'Tinashe Madzimbamuto'

env:
    FLUTTER_VERSION: "3.10.5"

runs:
  steps:
     - uses: actions/checkout@v3
            - name: Install Flutter
              uses: britannio/action-install-flutter@v1
              with:
                version: $FLUTTER_VERSION

            - name: Get packages
              run: flutter pub get

